const commonVariables = {
  VISIBLE_LAYER_DEFINING_VALUE: 0.4,
  MY_POSITION_ZOOM_LEVEL: 0.005,
  ANIMATION_SPEED: 1000,
  SEARCH_ZOOM_LEVEL: 0.01,
  SEARCH_ANIMATION_SPEED: 1000,
  SEARCH_DEBOUNCE: 500,
  SEARCH_MIN_CHAR_TRIGGER: 3,
};

export default commonVariables;
